### ISSUE TITLE
No issue in code but in web site documentation

### ISSUE THREAD

**Issue by paulcrawford** [tspspi/stepperDriverULM2003RS485#1]
I needed to add RS485 to my megaAT328p and a web search yielded your article [https://www.tspi.at/2021/02/10/rs485avr.html](url). The code described is definitely what I need although my adaptation will be much simpler as it for read only data from sensors. The link in the article brought me here. The code here specifies the use of PD3 to control RE and DE on the RS485 driver but the article states that:

> To allow easy switching between receive and transmit mode two functions are used. It’s assumed that the RE and DE pins of the RS485 are connected to PD2. RXD and TXD pins are hopefully obvious. 

Can you please edit the article to make it agree with the code?

**Comment by tspspi** [comment]
Wow thanks - this had to be a typo while writing that stuff up. Thanks very much! Will be fixed immediately (already pushed to the repo, the build system should update the page soon).

**Comment by paulcrawford** [comment]
Thanks for the quick response. And thanks even more for the code. I am presently porting it over to my own code.
